### ISSUE TITLE
Passing on Zoom Level to PostGIS

### ISSUE THREAD

**Issue by waissbluth** [nodetiles/nodetiles-postgis#4]
How can we go about passing on the current zoom level to PostGIS?

I'm guessing it would involve modifying the dataset API.

This would be really useful for performance reasons. For example, to leverage PostGIS's `ST_Simplify()` on low zoom levels.

Thanks!

**Comment by Mr0grog** [comment]
> I'm guessing it would involve modifying the dataset API.

That’s definitely true; the datasource API would have to have a backwards-incompatible change to support this. It’s really more a bug for [nodetiles-core](https://github.com/nodetiles/nodetiles-core) than for the PostGIS datasource.

As a side note, I don’t think zoom level is what you really want for line simplification—you really want to know what the pixels-to-projection-points ratio is (e.g. you’d want more detail for a zoom level 1 image that’s 1000px wide than you would for a zoom level 1 image that’s only 256px wide). It’s also worth noting that `zoom` is a totally optional parameter in NodeTiles, so even if it were passed to the datasource when present, the datasource couldn’t actually rely on receiving it.

It’s possible we’d be better off to just send the datasource all the same metadata that we are sending the renderer.

That said, if I were rebuilding NodeTiles again, I think I might architect it slightly differently and use the styling information to intelligently query datasources (so a datasource doesn’t have to deliver anything that won’t get rendered). I think the ideal scenario for all this is actually much different from the way it is now.

**Comment by Mr0grog** [comment]
Do you have a strong need for this, or is it just speculative?

You might have noticed that this isn’t really a very active project; I’m happy to do some light support work for people who have an immediate need (and happy to accept pull requests, too), but the truth is that these days @bensheldon, @yuletide, and myself haven’t had the time we’d originally hoped to actively work on it. More intense re-architecting is probably not something I’ll be able to make much time for soon.

**Comment by waissbluth** [comment]
Hey Rob, thanks for taking the time  to answer.

I'm not using this in production, but I'm playing around to see if I get
good results and can eventually deploy this.

What you say regarding zoom levels makes sense. Actually, yesterday I was
trying to work around this and I came up with an (untested) way of
adjusting for resolution.

```
// Map units per pixel
x_res = (max[0] - min[0])/256; // Assuming 256px tiles?
y_res = (max[1] - min[1])/256;
```

Passing on these
 values onto a PostGIS query might be useful for use in
`ST_Simplify()` or `ST_SnapToGrid()`.

I might be able to do on stuff in this direction, working towards a pull
request, but I'd appreciate your input.

**Comment by Mr0grog** [comment]
Hmmm, there are actually two pretty big confounding issues here now that I’m thinking more about it:

If your data source is in a different projection than the output map (for example, the data is in EPSG:4326—lat/long—and the map is in web mercator), simplifying in PG might not be a good idea since rendered pixels per datasource-projection-unit might vary across parts of the queried area. Or at least you might want to simplify less than you would in the optimal case. It might be better to eat it on the querying side and simplify after projecting. In that case, simplification might be better handled at some other level in the stack.

The second thing is that the datasource is missing another critical piece of information I forgot about yesterday—the bounds buffer size. Your formula would _almost_ get you map units per pixel, but datasources are actually queried with a geographic buffer—that is, a datasource gets asked for shapes covering a larger area than will actually be drawn. That’s because the styling may cause shapes that are entirely outside the rendered area to still overlap. Think really thick lines, shields, or labels, where the text spans far to the left and right of a point they are associated with. Ultimately, that means the min X value for the datasource is not the same as the left-most boundary of the rendered map image.

The default for that buffer in NodeTiles is 25% of the image width. (It’s stored on the `Map` instance as `mapInstance.boundsBuffer`, which may be a number or a function.) So you could never know for sure what it is :\  You could have the user optionally configure the data source with the buffer (or with a reference to the map and the datasource could grab the map’s `boundsBuffer`), but that’s kludgy enough that I think we might be better off just improving the datasource API instead.

**Comment by waissbluth** [comment]
Good point about the buffer, that might explain an issue I was encountering
with the precision of my simplification actually. I discovered I needed a
number larger than 256 (I ended up using 400) to get good results. Using
256*1.25=320 yields almost perfect results.

I believe that what you're saying regarding projection is yet another
reason to attempt PostGIS projection. Could you point out the main workflow
for implement this? I can give it a shot in the next few days, and then I
can come back to this issue without the problem you pointed out for large
geometries.

On Mon, May 4, 2015 at 2:23 PM, Rob Brackett notifications@github.com
wrote:

> Hmmm, there are actually two pretty big confounding issues here now that
> I’m thinking more about it:
> 
> If your data source is in a different projection than the output map (for
> example, the data is in EPSG:4326—lat/long—and the map is in web mercator),
> simplifying in PG might not be a good idea since rendered pixels per
> datasource-projection-unit might vary across parts of the queried area. Or
> at least you might want to simplify less than you would in the optimal
> case. It might be better to eat it on the querying side and simplify after
> projecting. In that case, simplification might be better handled at some
> other level in the stack.
> 
> The second thing is that the datasource is missing another critical piece
> of information I forgot about yesterday—the bounds buffer size. Your
> formula would _almost_ get you map units per pixel, but datasources are
> actually queried with a geographic buffer—that is, a datasource gets asked
> for shapes covering a larger area than will actually be drawn. That’s
> because the styling may cause shapes that are entirely outside the rendered
> area to still overlap. Think really thick lines, shields, or labels, where
> the text spans far to the left and right of a point they are associated
> with. Ultimately, that means the min X value for the datasource is not the
> same as the left-most boundary of the rendered map image.
> 
> The default for that buffer in NodeTiles is 25% of the map width. (It’s
> stored on the Map instance as mapInstance.boundsBuffer, which may be a
> number or a function.) So you could never know for sure what it is :\ You
> could have the user optionally configure the data source with the buffer
> (or with a reference to the map and the datasource could grab the map’s
> boundsBuffer), but that’s kludgy enough that I think we might be better
> off just improving the datasource API instead.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodetiles/nodetiles-postgis/issues/4#issuecomment-98785543
> .

## 

Nicolás Waissbluth Razmilic

**Comment by Mr0grog** [comment]
> Using 256*1.25=320 yields almost perfect results.

I _should_ be `256 * 1.5`, I think. The buffer is applied on all four sides—you can see the implementation in NodeTiles: https://github.com/nodetiles/nodetiles-core/blob/master/lib/Map.js#L121

> another reason to attempt PostGIS projection

So there are a few reasons this isn’t done currently is because it’s enormously hard to do generically. In order for it to work, the user has to have all the relevant projection data also stored in their database. They also have to have built PG with Proj4 support. Those are both additional requirements for users and hard to validate performantly. NodeTiles might also be lacking in the relevant info to look up the right projection info in PG, too. Not 100% sure on that one.

But if you wanted to do this, the datasource is supplied with the intended output projection (5th argument to `getShapes()`), so the datasource should already be receiving everything it needs for that. IIRC, it can be a Proj4 instance or a string like “EPSG:####”, though I think the former is not actually supported in this datasource—not sure why; @yuletide originally wrote it.

**Comment by waissbluth** [comment]
Ha, that was the "almost" then. 256*1.5 it is.

Ok then, I think that having PostGIS projection enabled by an option (i.e.
the user must already know if PostGIS projection is feasible) might make
sense for now. I'll look into it #5

On Mon, May 4, 2015 at 3:41 PM, Rob Brackett notifications@github.com
wrote:

> Using 256*1.25=320 yields almost perfect results.
> 
> I _should_ be 256 \* 1.5, I think. The buffer is applied on all four
> sides—you can see the implementation in NodeTiles:
> https://github.com/nodetiles/nodetiles-core/blob/master/lib/Map.js#L121
> 
> another reason to attempt PostGIS projection
> 
> So there are a few reasons this isn’t done currently is because it’s
> enormously hard to do generically. In order for it to work, the user has to
> have all the relevant projection data also stored in their database. They
> also have to have built PG with Proj4 support. Those are both additional
> requirements for users and hard to validate performantly. NodeTiles might
> also be lacking in the relevant info to look up the right projection info
> in PG, too. Not 100% sure on that one.
> 
> But if you wanted to do this, the datasource is supplied with the intended
> output projection (5th argument to getShapes()), so the datasource should
> already be receiving everything it needs for that. IIRC, it can be a Proj4
> instance or a string like “EPSG:####”, though I think the former is not
> actually supported in this datasource—not sure why; @yuletide
> https://github.com/yuletide originally wrote it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodetiles/nodetiles-postgis/issues/4#issuecomment-98809553
> .

## 

Nicolás Waissbluth Razmilic

**Comment by Mr0grog** [comment]
An option seems reasonable. Looking at the PG docs, it seems like you’d have to query the DB to find the SRID to use for `ST_Transform`. Maybe something like (untested):

``` javascript
var knownSrids = {};
function getDbSrid(projection, callback) {
  if (knownSrids[projection]) {
    return callback(null, knownSrids[projection]);
  }
  var projectionParts = projection.split(":");
  var query;
  if (projectionParts.length > 1) {
    // name and code, e.g. "EPSG:4326"
    query = "SELECT srid FROM spatial_ref_sys WHERE auth_name = $1 AND auth_srid = $2";
  }
  else {
    // Proj4 String, this is especially iffy
   query = "SELECT srid FROM spatial_ref_sys WHERE trim(from proj4text) = $1"
  }
  pgClient.query(query, projectionParts, function(error, result) {
    // if found, save SRID for use when querying shapes
    // otherwise, the implementation should fall back to projecting in JS as it currently does
    if (foundSrid) {
      knownSrids[projection] = foundSrid;
    }
    return callback(null, knownSrids[projection]);
  });
}
```

You could probably keep a hash mapping NodeTiles projections to SRIDs in the database so you only have to look it up once for each unique projection you ever receive a query from.

The setup options for the DB could maybe include values with which to pre-populate `knownSrids`.

**Comment by waissbluth** [comment]
Hey Rob,

After going crazy for a while trying to get this to work, I realised that for my use case (only points, huge amount of data, table joins in between, and zoom-level based queries) is better for me to write a custom PostGIS datasource.

For now I'm working on a fork of this repository and maybe I'll back with what I learn to implement some of the stuff here if it's useful.

Thanks!

**Comment by Mr0grog** [comment]
Yep, sounds like your use case is a little complicated for the generic datasource, but that is indeed why they’re pluggable :)

I’ll close this, if that’s alright?
